<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class HotelPromoSeeder extends Seeder
{
    public function run()
        {
            DB::table('hotel_promos')->insert(
                [
                    [
                        'hotels_id'=>1,
                        'rooms_id'=>1,
                        'name' => 'Low Season',
                        'minimum_stay'=>2,
                        'book_periode_start'=>'2022-08-01',
                        'book_periode_end'=>'2022-12-01',
                        'periode_start'=>'2022-11-01',
                        'periode_end'=>'2022-12-01',
                        'booking_code'=>'AKSHDB123',
                        'benefits'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                        'contract_rate' => rand(1000000, 10000000),
                        'markup' => 5,
                        'status'=> 'Active',
                        'author'=>1,
                        'include'=> 'Breakfast, SPA (2 Hours), Dinner',
                        'additional_info'=>'Available only on Booking Period',
                    ],
                    [
                        'hotels_id'=>1,
                        'rooms_id'=>2,
                        'name' => 'Low Season',
                        'author'=>1,
                        'minimum_stay'=>2,
                        'book_periode_start'=>'2022-08-01',
                        'book_periode_end'=>'2022-12-01',
                        'periode_start'=>'2022-11-01',
                        'periode_end'=>'2022-12-01',
                        'booking_code'=>'AKSHDB123',
                        'benefits'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                        'contract_rate' => rand(1000000, 10000000),
                        'markup' => 5,
                        'status'=> 'Active',
                        'include'=> 'Breakfast, SPA (2 Hours), Dinner',
                        'additional_info'=>'Available only on Booking Period',
                    ],
                    [
                        'hotels_id'=>1,
                        'rooms_id'=>3,
                        'minimum_stay'=>2,
                        'name' => 'Low Season',
                        'author'=>1,
                        'book_periode_start'=>'2022-08-01',
                        'book_periode_end'=>'2022-12-01',
                        'periode_start'=>'2022-11-01',
                        'periode_end'=>'2022-12-01',
                        'booking_code'=>'AKSHDB123',
                        'benefits'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                        'contract_rate' => rand(1000000, 10000000),
                        'markup' => 5,
                        'status'=> 'Active',
                        'include'=> 'Breakfast, SPA (2 Hours), Dinner',
                        'additional_info'=>'Available only on Booking Period',
                    ],
                    [
                        'hotels_id'=>1,
                        'rooms_id'=>1,
                        'author'=>1,
                        'minimum_stay'=>2,
                        'name' => 'Low Season',
                        'book_periode_start'=>'2022-08-01',
                        'book_periode_end'=>'2022-12-01',
                        'periode_start'=>'2023-01-01',
                        'periode_end'=>'2023-02-01',
                        'booking_code'=>'AKSHDB123',
                        'benefits'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                        'contract_rate' => rand(1000000, 10000000),
                        'markup' => 5,
                        'status'=> 'Active',
                        'include'=> 'Breakfast, SPA (2 Hours), Dinner',
                        'additional_info'=>'Available only on Booking Period',
                    ],
                    [
                        'hotels_id'=>1,
                        'rooms_id'=>2,
                        'author'=>1,
                        'minimum_stay'=>2,
                        'name' => 'Low Season',
                        'book_periode_start'=>'2022-08-01',
                        'book_periode_end'=>'2022-12-01',
                        'periode_start'=>'2023-01-01',
                        'periode_end'=>'2023-02-01',
                        'booking_code'=>'AKSHDB123',
                        'benefits'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                        'contract_rate' => rand(1000000, 10000000),
                        'markup' => 5,
                        'status'=> 'Active',
                        'include'=> 'Breakfast, SPA (2 Hours), Dinner',
                        'additional_info'=>'Available only on Booking Period',
                    ],
                    [
                        'hotels_id'=>1,
                        'rooms_id'=>3,
                        'author'=>1,
                        'minimum_stay'=>2,
                        'name' => 'Low Season',
                        'book_periode_start'=>'2022-08-01',
                        'book_periode_end'=>'2022-12-01',
                        'periode_start'=>'2023-01-01',
                        'periode_end'=>'2023-02-01',
                        'booking_code'=>'AKSHDB123',
                        'benefits'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                        'contract_rate' => rand(1000000, 10000000),
                        'markup' => 5,
                        'status'=> 'Active',
                        'include'=> 'Breakfast, SPA (2 Hours), Dinner',
                        'additional_info'=>'Available only on Booking Period',
                    ],
                    [
                        'hotels_id'=>1,
                        'rooms_id'=>1,
                        'author'=>1,
                        'minimum_stay'=>2,
                        'name' => 'Low Season',
                        'book_periode_start'=>'2022-08-01',
                        'book_periode_end'=>'2022-12-01',
                        'periode_start'=>'2023-03-01',
                        'periode_end'=>'2023-04-01',
                        'booking_code'=>'AKSHDB123',
                        'benefits'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                        'contract_rate' => rand(1000000, 10000000),
                        'markup' => 5,
                        'status'=> 'Active',
                        'include'=> 'Breakfast, SPA (2 Hours), Dinner',
                        'additional_info'=>'Available only on Booking Period',
                    ],
                    [
                        'hotels_id'=>1,
                        'rooms_id'=>2,
                        'author'=>1,
                        'minimum_stay'=>2,
                        'name' => 'Low Season',
                        'book_periode_start'=>'2022-08-01',
                        'book_periode_end'=>'2022-12-01',
                        'periode_start'=>'2023-03-01',
                        'periode_end'=>'2023-04-01',
                        'booking_code'=>'AKSHDB123',
                        'benefits'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                        'contract_rate' => rand(1000000, 10000000),
                        'markup' => 5,
                        'status'=> 'Active',
                        'include'=> 'Breakfast, SPA (2 Hours), Dinner',
                        'additional_info'=>'Available only on Booking Period',
                    ],
                    [
                        'hotels_id'=>1,
                        'rooms_id'=>3,
                        'author'=>1,
                        'minimum_stay'=>2,
                        'name' => 'Low Season',
                        'book_periode_start'=>'2022-08-01',
                        'book_periode_end'=>'2022-12-01',
                        'periode_start'=>'2023-03-01',
                        'periode_end'=>'2023-04-01',
                        'booking_code'=>'AKSHDB123',
                        'benefits'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                        'contract_rate' => rand(1000000, 10000000),
                        'markup' => 5,
                        'status'=> 'Active',
                        'include'=> 'Breakfast, SPA (2 Hours), Dinner',
                        'additional_info'=>'Available only on Booking Period',
                    ],
                    [
                        'hotels_id'=>1,
                        'rooms_id'=>1,
                        'author'=>1,
                        'minimum_stay'=>2,
                        'name' => 'Low Season',
                        'book_periode_start'=>'2022-08-01',
                        'book_periode_end'=>'2022-12-01',
                        'periode_start'=>'2023-05-01',
                        'periode_end'=>'2023-06-01',
                        'booking_code'=>'AKSHDB123',
                        'benefits'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                        'contract_rate' => rand(1000000, 10000000),
                        'markup' => 5,
                        'status'=> 'Active',
                        'include'=> 'Breakfast, SPA (2 Hours), Dinner',
                        'additional_info'=>'Available only on Booking Period',
                    ],
                    [
                        'hotels_id'=>1,
                        'rooms_id'=>2,
                        'author'=>1,
                        'minimum_stay'=>2,
                        'name' => 'Low Season',
                        'book_periode_start'=>'2022-08-01',
                        'book_periode_end'=>'2022-12-01',
                        'periode_start'=>'2023-05-01',
                        'periode_end'=>'2023-06-01',
                        'booking_code'=>'AKSHDB123',
                        'benefits'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                        'contract_rate' => rand(1000000, 10000000),
                        'markup' => 5,
                        'status'=> 'Active',
                        'include'=> 'Breakfast, SPA (2 Hours), Dinner',
                        'additional_info'=>'Available only on Booking Period',
                    ],
                    [
                        'hotels_id'=>1,
                        'rooms_id'=>3,
                        'author'=>1,
                        'minimum_stay'=>2,
                        'name' => 'Low Season',
                        'book_periode_start'=>'2022-08-01',
                        'book_periode_end'=>'2022-12-01',
                        'periode_start'=>'2023-05-01',
                        'periode_end'=>'2023-06-01',
                        'booking_code'=>'AKSHDB123',
                        'benefits'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                        'contract_rate' => rand(1000000, 10000000),
                        'markup' => 5,
                        'status'=> 'Active',
                        'include'=> 'Breakfast, SPA (2 Hours), Dinner',
                        'additional_info'=>'Available only on Booking Period',
                    ],
                    [
                        'hotels_id'=>1,
                        'rooms_id'=>1,
                        'author'=>1,
                        'minimum_stay'=>2,
                        'name' => 'Low Season',
                        'book_periode_start'=>'2022-08-01',
                        'book_periode_end'=>'2022-12-01',
                        'periode_start'=>'2023-07-01',
                        'periode_end'=>'2023-08-01',
                        'booking_code'=>'AKSHDB123',
                        'benefits'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                        'contract_rate' => rand(1000000, 10000000),
                        'markup' => 5,
                        'status'=> 'Active',
                        'include'=> 'Breakfast, SPA (2 Hours), Dinner',
                        'additional_info'=>'Available only on Booking Period',
                    ],
                    [
                        'hotels_id'=>1,
                        'rooms_id'=>2,
                        'author'=>1,
                        'minimum_stay'=>2,
                        'name' => 'Low Season',
                        'book_periode_start'=>'2022-08-01',
                        'book_periode_end'=>'2022-12-01',
                        'periode_start'=>'2023-07-01',
                        'periode_end'=>'2023-08-01',
                        'booking_code'=>'AKSHDB123',
                        'benefits'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                        'contract_rate' => rand(1000000, 10000000),
                        'markup' => 5,
                        'status'=> 'Active',
                        'include'=> 'Breakfast, SPA (2 Hours), Dinner',
                        'additional_info'=>'Available only on Booking Period',
                    ],
                    [
                        'hotels_id'=>1,
                        'rooms_id'=>3,
                        'author'=>1,
                        'minimum_stay'=>2,
                        'name' => 'Low Season',
                        'book_periode_start'=>'2022-08-01',
                        'book_periode_end'=>'2022-12-01',
                        'periode_start'=>'2023-07-01',
                        'periode_end'=>'2023-08-01',
                        'booking_code'=>'AKSHDB123',
                        'benefits'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                        'contract_rate' => rand(1000000, 100000000),
                        'markup' => 5,
                        'status'=> 'Active',
                        'include'=> 'Breakfast, SPA (2 Hours), Dinner',
                        'additional_info'=>'Available only on Booking Period',
                    ],
                    [
                        'hotels_id'=>1,
                        'rooms_id'=>1,
                        'author'=>1,
                        'minimum_stay'=>2,
                        'name' => 'Low Season',
                        'book_periode_start'=>'2022-08-01',
                        'book_periode_end'=>'2022-12-01',
                        'periode_start'=>'2023-09-01',
                        'periode_end'=>'2023-10-01',
                        'booking_code'=>'AKSHDB123',
                        'benefits'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                        'contract_rate' => rand(1000000, 10000000),
                        'markup' => 5,
                        'status'=> 'Active',
                        'include'=> 'Breakfast, SPA (2 Hours), Dinner',
                        'additional_info'=>'Available only on Booking Period',
                    ],
                    [
                        'hotels_id'=>1,
                        'rooms_id'=>2,
                        'author'=>1,
                        'minimum_stay'=>2,
                        'name' => 'Low Season',
                        'book_periode_start'=>'2022-08-01',
                        'book_periode_end'=>'2022-12-01',
                        'periode_start'=>'2023-09-01',
                        'periode_end'=>'2023-10-01',
                        'booking_code'=>'AKSHDB123',
                        'benefits'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                        'contract_rate' => rand(1000000, 10000000),
                        'markup' => 5,
                        'status'=> 'Active',
                        'include'=> 'Breakfast, SPA (2 Hours), Dinner',
                        'additional_info'=>'Available only on Booking Period',
                    ],
                    [
                        'hotels_id'=>1,
                        'rooms_id'=>3,
                        'author'=>1,
                        'minimum_stay'=>2,
                        'name' => 'Low Season',
                        'book_periode_start'=>'2022-08-01',
                        'book_periode_end'=>'2022-12-01',
                        'periode_start'=>'2023-09-01',
                        'periode_end'=>'2023-10-01',
                        'booking_code'=>'AKSHDB123',
                        'benefits'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                        'contract_rate' => rand(1000000, 10000000),
                        'markup' => 5,
                        'status'=> 'Active',
                        'include'=> 'Breakfast, SPA (2 Hours), Dinner',
                        'additional_info'=>'Available only on Booking Period',
                    ],
                ]);
    }
}
